name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t api99/docker-react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true api99/docker-react-test npm test


      - run: docker build -t api99/multi-client ./client
      - run: docker build -t api99/multi-nginx ./nginx
      - run: docker build -t api99/multi-server ./server
      - run: docker build -t api99/multi-worker ./worker

#      - run: docker push api99/docker-react

      - run: docker push api99/multi-client
      - run: docker push api99/multi-nginx
      - run: docker push api99/multi-server
      - run: docker push api99/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

#      - name: Deploy to EB
#        uses: einaregilsson/beanstalk-deploy@v14 # custom github action, don't change
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#          application_name: docker-react
#          environment_name: Docker-react-env
#          existing_bucket_name: elasticbeanstalk-eu-central-1-729632440439
#          region: eu-central-1
#          version_label: ${{ github.sha }}
#          deployment_package: deploy.zip